/**
 * The service worker, served from a route rather than /public.
 *
 * Why not a static file: a service worker's cache name has to change on every
 * deploy or old assets are served forever. The previous version hardcoded
 * `CACHE_NAME = "my-duty-pwa-v2"`, which meant remembering to bump a string by
 * hand on every release — a step that gets forgotten exactly once and then
 * never noticed. Generating the file here stamps the build automatically.
 *
 * `force-static` makes this evaluate at BUILD time, so BUILD_VERSION is fixed
 * per deploy rather than changing on every request (which would make the
 * browser think there was a new worker every single time it checked).
 */
export const dynamic = "force-static";

const BUILD_VERSION =
  process.env.VERCEL_GIT_COMMIT_SHA?.slice(0, 12) ?? String(Date.now());

const SW = /* js */ `
// My Duty — Gujarat Police Portal service worker
// Generated at build time. Do not edit a cached copy; edit src/app/sw.js/route.ts.
const VERSION = ${JSON.stringify(BUILD_VERSION)};
const CACHE_NAME = "my-duty-" + VERSION;
const OFFLINE_URL = "/offline";

// Only things that are the same for everyone. Officer data is deliberately
// absent — see the fetch handler.
const PRECACHE = [
  OFFLINE_URL,
  // Generated by src/app/manifest.ts. A duplicate public/manifest.json used to
  // sit beside it, unreferenced and free to drift out of sync — removed.
  "/manifest.webmanifest",
  "/favicon.ico",
  "/Gujarat-police.png",
  "/apple-touch-icon.png",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-192.png",
  "/icons/icon-maskable-512.png",
];

self.addEventListener("install", (event) => {
  event.waitUntil(
    caches.open(CACHE_NAME).then((cache) =>
      cache.addAll(PRECACHE).catch((err) => {
        console.warn("[SW] some assets failed to precache:", err);
      })
    )
  );
  // NO skipWaiting() here on purpose.
  //
  // Activating immediately swaps the worker underneath a page that is still
  // running the OLD JavaScript bundle. That page can then request a code chunk
  // the new deploy deleted and fail — and it would happen mid-form, losing
  // whatever was typed. Instead the new worker waits, the page notices it and
  // offers a reload, and SKIP_WAITING below runs only when the officer agrees.
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((names) =>
        Promise.all(
          names.filter((n) => n !== CACHE_NAME).map((n) => caches.delete(n))
        )
      )
      .then(() => self.clients.claim())
  );
});

// The page asks for the update once the officer taps Reload.
self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "SKIP_WAITING") {
    self.skipWaiting();
  }
});

self.addEventListener("fetch", (event) => {
  const { request } = event;

  // Never touch writes, cross-origin calls, or Supabase.
  if (request.method !== "GET") return;

  const url = new URL(request.url);
  if (url.origin !== self.location.origin) return;

  // Never cache API routes: they carry one officer's data and a signed URL.
  if (url.pathname.startsWith("/api/")) return;

  // Shared, immutable assets: cache-first. Next fingerprints its own chunks,
  // and these are identical for every officer, so nothing personal is stored.
  const isSharedAsset =
    url.pathname.startsWith("/icons/") ||
    url.pathname === "/manifest.webmanifest" ||
    /\\.(png|ico|svg|woff2?)$/.test(url.pathname);

  if (isSharedAsset) {
    event.respondWith(
      caches.match(request).then(
        (hit) =>
          hit ||
          fetch(request).then((res) => {
            if (res && res.status === 200) {
              const copy = res.clone();
              caches.open(CACHE_NAME).then((c) => c.put(request, copy));
            }
            return res;
          })
      )
    );
    return;
  }

  // Pages: always from the network, and NEVER written to the cache.
  //
  // The previous worker cached every navigation, including /dashboard and
  // /duty. On a shared phone that meant a second officer going offline could
  // be served the first officer's pages out of the cache. Offline now shows a
  // notice instead of somebody else's data.
  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).catch(() =>
        caches.match(OFFLINE_URL).then(
          (page) =>
            page ||
            new Response("You are offline.", {
              status: 503,
              headers: { "Content-Type": "text/plain" },
            })
        )
      )
    );
  }
});
`;

export function GET() {
  return new Response(SW, {
    headers: {
      "Content-Type": "text/javascript; charset=utf-8",
      // The worker script itself must never be held in the HTTP cache, or the
      // browser cannot discover that a new version exists.
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Service-Worker-Allowed": "/",
    },
  });
}
